Config = {

VehicleBlacklist = true,     -- Enable or Disable Vehicle Blacklist (true or false)
PedBlacklist = true,         -- Enable or Disable Ped Blacklist (true or false)
WeaponBlacklist = true,      -- Enable or Disable Weapon Blacklist (true or false)

VehBlacklistMessage = "This vehicle has been restricted, Please find another one!!",     -- Message Displayed when vehicle is deleted
PedBlacklistMessage = "This ped has been restricted, Please find another one!!",         -- Message Displayed when ped is deleted
WepBlacklistMessage = "This weapon has been restricted, Please use another one!!",       -- Message Displayed when weapon is deleted

DefaultPed = "a_m_y_yoga_01", -- https://docs.fivem.net/docs/game-references/ped-models/

}

Config.Bypass = {

Bypass = true, -- Enable or disable AcePerm Bypass (true or false)

VehBypass = "AJ:VehBypass", -- This is your ACE Perm String. I suggest leaving it as is
PedBypass = "AJ:PedBypass", -- This is your ACE Perm String. I suggest leaving it as is
WepBypass = "AJ:WepBypass",  -- This is your ACE Perm String. I suggest leaving it as is

}

Config.VehBlacklist = { -- https://docs.fivem.net/docs/game-references/vehicle-models/
    "akula",
    "alkonost",
    "alphaz1",
    "ambulance",
    "annihilator",
    "annihilator2",
    "apc",
    "armytanker",
    "armytrailer",
    "armytrailer2",
    "avenger",
    "avenger2",
    "avenger3",
    "avenger4",
    "barracks",
    "barracks2",
    "barracks3",
    "barrage",
    "besra",
    "blazer5",
    "blimp",
    "blimp2",
    "blimp3",
    "bombushka",
    "boxville5",
    "bruiser",
    "bruiser2",
    "bruiser3",
    "bulldozer",
    "buzzard",
    "buzzard2",
    "cablecar",
    "caracara",
    "cargobob",
    "cargobob2",
    "cargobob3",
    "cargobob4",
    "cargoplane",
    "cargoplane2",
    "casco",
    "cerberus",
    "cerberus2",
    "cerberus3",
    "chernobog",
    "conada",
    "conada2",
    "cuban800",
    "cutter",
    "dinghy5",
    "dodo",
    "dukes2",
    "dump",
    "dune4",
    "dune5",
    "duster",
    "fbi",
    "fbi2",
    "firetruk",
    "formula",
    "formula2",
    "freight",
    "freight2",
    "freightcar",
    "freightcar2",
    "freightcont1",
    "freightcont2",
    "freightgrain",
    "freighttrailer",
    "frogger",
    "frogger2",
    "halftrack",
    "handler",
    "havok",
    "howard",
    "hunter",
    "hydra",
    "insurgent",
    "insurgent2",
    "insurgent3",
    "jet",
    "khanjali",
    "kosatka",
    "lazer",
    "luxor",
    "luxor2",
    "mammatus",
    "marquis",
    "maverick",
    "mesa3",
    "microlight",
    "miljet",
    "minitank",
    "mogul",
    "molotok",
    "monster",
    "monster3",
    "monster4",
    "monster5",
    "nightshark",
    "nimbus",
    "nokota",
    "openwheel1",
    "openwheel2",
    "oppressor",
    "oppressor2",
    "patrolboat",
    "pbus",
    "phantom2",
    "polgauntlet",
    "police",
    "police2",
    "police3",
    "police4",
    "police5",
    "policeb",
    "policeold1",
    "policeold2",
    "policet",
    "polmav",
    "pranger",
    "predator",
    "proptrailer",
    "pyro",
    "raiju",
    "raketrailer",
    "rallytruck",
    "rhino",
    "riot",
    "riot2",
    "ripley",
    "rogue",
    "ruiner3",
    "savage",
    "scarab",
    "scarab2",
    "scarab3",
    "seabreeze",
    "shamal",
    "sheriff2",
    "skylift",
    "starling",
    "stockade",
    "stockade3",
    "streamer216",
    "strikeforce",
    "stunt",
    "supervolito",
    "supervolito2",
    "swift",
    "swift2",
    "tampa3",
    "tanker",
    "tanker2",
    "tankercar",
    "technical",
    "technical2",
    "technical3",
    "thruster",
    "titan",
    "tr2",
    "tr3",
    "tr4",
    "trailersmall2",
    "trflat",
    "tug",
    "tula",
    "utillitruck",
    "utillitruck2",
    "utillitruck3",
    "valkyrie",
    "valkyrie2",
    "velum",
    "velum2",
    "vestra",
    "vindicator",
    "volatol",
    "volatus"
}

Config.PedBlacklist = { -- https://docs.fivem.net/docs/game-references/ped-models/
    "a_c_killerwhale",
    "a_c_sharkhammer"
}

Config.WepBlacklist = { -- https://vespura.com/fivem/weapons/stats/
    "weapon_autoshotgun",
    "weapon_bzgas",
    "weapon_compactlauncher",
    "weapon_grenade",
    "weapon_grenadelauncher",
    "weapon_heavysniper",
    "weapon_hominglauncher",
    "weapon_minigun",
    "weapon_pipebomb",
    "weapon_proxmine",
    "weapon_railgun",
    "weapon_rpg",
    "weapon_smokegrenade",
    "weapon_sniperrifle",
    "weapon_stickybomb",
    "weapon_raypistol",
    "weapon_raycarbine",
    "weapon_rayminigun"
}